### PR TITLE
Add almalinux 8

### PR DESCRIPTION
**Pull request by ArtofBugs**

### CODE REVIEW

**Comment by ramereth** [comment]
@ArtofBugs so this cookbook hasn't been used in a while and needs a little bit if work to get it fixed. If you're willing to do it, that would be great in case we ever needed this again.

Primarily, this still references a deprecreated firewall cookbook. This should be migrated to using our osl-firewall cookbook. Would you mind doing that please?

**Comment by ArtofBugs** [comment]
Sure! I might be working on it in on the side mostly while doing customer support stuff this week, but I can definitely dedicate some more time to it when I'm done with those.

**Comment by ramereth** [comment]
!bump major ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v3.0.0.  Have a nice day!

**Pull request merged**
